# Generated by Django 4.0.3 on 2023-02-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_faq_mainregistration_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('youtubelink', models.CharField(max_length=50)),
                ('discription', models.TextField()),
            ],
        ),
    ]
