# Generated by Django 4.0.3 on 2023-02-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_vlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainregistration',
            name='phono',
            field=models.CharField(default=2, max_length=250, verbose_name='Phono no'),
            preserve_default=False,
        ),
    ]
