# Generated by Django 4.0.3 on 2023-02-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmonial',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='testmonial',
            name='title',
        ),
        migrations.RemoveField(
            model_name='testmonial',
            name='youtubelink',
        ),
        migrations.AddField(
            model_name='testmonial',
            name='content',
            field=models.TextField(default=3, verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testmonial',
            name='name',
            field=models.CharField(default=2, max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testmonial',
            name='origin',
            field=models.CharField(default=2, max_length=50, verbose_name='origin'),
            preserve_default=False,
        ),
    ]
