# Generated by Django 4.0.3 on 2023-02-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_remove_testmonial_discription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmonial',
            name='content',
        ),
        migrations.AddField(
            model_name='testmonial',
            name='discription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testmonial',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testmonial',
            name='origin',
            field=models.CharField(max_length=50),
        ),
    ]
