# Generated by Django 4.0.3 on 2023-02-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_remove_testmonial_content_testmonial_discription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoTestmonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('youtubelink', models.CharField(max_length=50)),
            ],
        ),
    ]
