# Generated by Django 4.0.3 on 2023-02-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=1000, unique=True),
            preserve_default=False,
        ),
    ]
