# Generated by Django 4.0.3 on 2023-03-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_alter_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='visasuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('title', models.CharField(max_length=150, verbose_name='Origin')),
                ('discripton', models.CharField(max_length=150, verbose_name='Discription ( only 150 lines )')),
                ('img', models.ImageField(upload_to='visasuccess', verbose_name='Profile photo')),
            ],
        ),
    ]
