# Generated by Django 4.0.3 on 2023-03-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_visasuccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='companytestmonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('origin', models.CharField(max_length=150, verbose_name='Origin')),
                ('dis', models.CharField(max_length=250, verbose_name='Discription')),
                ('img', models.ImageField(upload_to='company Testmonial University image', verbose_name='Image')),
            ],
        ),
    ]
