# Generated by Django 4.0.3 on 2023-03-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_newsletters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletters',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
